# All host ports incremented by 10.
version: "3"
services:
  redis-test:
    image: "graphion-redis"
    networks:
      - "graphion-network-test"
    ports:
      - "6389:6379"
    volumes:
      - "graphion-redis-test-volume:/data"
    restart: "always"
  db-test:
    image: "graphion-db"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_SCHEMA: "${POSTGRES_SCHEMA}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_UNPRIV_USER: "${POSTGRES_UNPRIV_USER}"
    networks:
      - "graphion-network-test"
    ports:
      - "5442:5432"
    volumes:
      - "graphion-db-test-volume:/var/lib/postgresql/data/"
    restart: "always"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: "5s"
      timeout: "5s"
      retries: 5
  minio-server-test:
    image: "graphion-minio-server"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_CONFIG_ENV_FILE: "/etc/minio-server.conf"
    networks:
      - "graphion-network-test"
    ports:
     - "9010:9000"
     - "9011:9001"
    volumes:
      - "graphion-minio-test-volume:/data"
    restart: "always"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: "5s"
      timeout: "5s"
      retries: 5
  minio-client-test:
    depends_on:
      - "minio-server-test"
    build:
      context: "./minio-client"
      dockerfile: Dockerfile
    image: "graphion-minio-client-test"
    environment:
      MINIO_SERVER: "${MINIO_SERVER_TEST}"
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_UNPRIV_USER: "${MINIO_UNPRIV_USER}"
      MINIO_UNPRIV_PASSWORD: "${MINIO_UNPRIV_PASSWORD}"
    networks:
      - "graphion-network-test"
  mailhog-test:
    image: "mailhog/mailhog:latest"
    networks:
      - graphion-network-test
    ports:
      - "1035:1025"
      - "8035:8025"
    restart: "always"

  # reverseproxy:
  #   build:
  #     context: "./nginx"
  #     dockerfile: "Dockerfile"
  #   image: "graphion-reverseproxy"
  #   network_mode: "host"
  #   ports:
  #     - "8443:8443"
  #   restart: "always"
  # scraper:
  #   build:
  #     context: "."
  #     dockerfile: "Dockerfile"
  #   image: "scraper"
  #   networks:
  #     - "graphion-network-test"
  #   security_opt:
  #     - "seccomp=playwright/seccomp_profile.json"
  #   depends_on:
  #     - "redis"
  # eid:
  #   build:
  #     context: "../eid"
  #     dockerfile: "Dockerfile"
  #   image: "graphion-eid"
  #   networks:
  #     - "graphion-network-test"
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - "db"

networks:
  graphion-network-test:
    name: "graphion-network-test"
    driver: "bridge"

volumes:
  graphion-redis-test-volume:
    name: "graphion-redis-test-volume"
  graphion-db-test-volume:
    name: "graphion-db-test-volume"
  graphion-minio-test-volume:
    name: "graphion-minio-test-volume"
