# All host ports incremented by 10.
version: "3"
name: "graphion-test"
services:
  redis:
    image: "graphion-redis"
    networks:
      - "graphion-test-network"
    ports:
      - "6389:6379"
    volumes:
      - "graphion-test-redis-volume:/data"
    restart: "always"
  postgres:
    image: "graphion-postgres"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_SCHEMA: "${POSTGRES_SCHEMA}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_UNPRIV_USER_SCA_WEB: "${POSTGRES_UNPRIV_USER_SCA_WEB}"
      POSTGRES_UNPRIV_USER_SCA_WORKER: "${POSTGRES_UNPRIV_USER_SCA_WORKER}"
    networks:
      - "graphion-test-network"
    ports:
      - "5442:5432"
    volumes:
      - "graphion-test-postgres-volume:/var/lib/postgresql/data/"
    restart: "always"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: "5s"
      timeout: "5s"
      retries: 5
  minio-server:
    image: "graphion-minio-server"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_CONFIG_ENV_FILE: "/etc/minio-server.conf"
    networks:
      - "graphion-test-network"
    ports:
     - "9010:9000"
     - "9011:9001"
    volumes:
      - "graphion-test-minio-volume:/data"
    restart: "always"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: "5s"
      timeout: "5s"
      retries: 5
  minio-client:
    image: "graphion-minio-client"
    environment:
      MINIO_HOST: "${MINIO_HOST}"
      MINIO_PORT: "${MINIO_PORT}"
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_UNPRIV_USER: "${MINIO_UNPRIV_USER}"
      MINIO_UNPRIV_PASSWORD: "${MINIO_UNPRIV_PASSWORD}"
      MINIO_BUCKET: "${MINIO_BUCKET}"
    networks:
      - "graphion-test-network"
    stop_grace_period: "1s"
  mailhog:
    image: "mailhog/mailhog:latest"
    networks:
      - graphion-test-network
    ports:
      - "1035:1025"
      - "8035:8025"
    restart: "always"

  # reverseproxy:
  #   build:
  #     context: "./nginx"
  #     dockerfile: "Dockerfile"
  #   image: "graphion-reverseproxy"
  #   network_mode: "host"
  #   ports:
  #     - "8443:8443"
  #   restart: "always"
  # scraper:
  #   build:
  #     context: "."
  #     dockerfile: "Dockerfile"
  #   image: "scraper"
  #   networks:
  #     - "graphion-test-network"
  #   security_opt:
  #     - "seccomp=playwright/seccomp_profile.json"
  #   depends_on:
  #     - "redis"
  # eid:
  #   build:
  #     context: "../eid"
  #     dockerfile: "Dockerfile"
  #   image: "graphion-eid"
  #   networks:
  #     - "graphion-test-network"
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - "postgres"

networks:
  graphion-test-network:
    name: "graphion-test-network"
    driver: "bridge"

volumes:
  graphion-test-redis-volume:
    name: "graphion-test-redis-volume"
  graphion-test-postgres-volume:
    name: "graphion-test-postgres-volume"
  graphion-test-minio-volume:
    name: "graphion-test-minio-volume"
