#!/bin/bash
set -e

psql -v --username "postgres" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE $POSTGRES_UNPRIV_USER WITH LOGIN ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';
	DROP SCHEMA IF EXISTS eid CASCADE;
	CREATE SCHEMA eid;
	ALTER SCHEMA eid OWNER TO $POSTGRES_UNPRIV_USER;
EOSQL
