#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE ROLE $POSTGRES_UNPRIV_USER WITH LOGIN ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';
	DROP SCHEMA IF EXISTS $POSTGRES_SCHEMA CASCADE;
	CREATE SCHEMA $POSTGRES_SCHEMA;
	ALTER SCHEMA $POSTGRES_SCHEMA OWNER TO $POSTGRES_UNPRIV_USER;
EOSQL
